chore(frontend): prevent env leak vulnerability
vpnhouse/tunnel pull request #70
Opened 2022-04-20 18:44 UTC by instingt

# Motivation
There is a possibility of leaking all ENV variables from build agent. It's good practice to whitelist variables
![telegram-cloud-photo-size-2-5404735284660255760-y](https://user-images.githubusercontent.com/1387604/164300735-dca98990-69db-4d1c-8dbf-ca3183069dd2.jpg)

2022-04-20 19:53 UTC, instingt commented
Removed the use of API_URL as it makes no sense: the front is built on CI and API_URL is "hardcoded" into the bundle and can no longer be changed. If a user wants to run the image behind a reverse proxy, he will not be able to change the API_URL and all requests will go to localhost:80 in general. I also added a --api parameter to the `npm start` command, where the url to the api backend is specified. See frontend/README.MD

Translated with www.DeepL.com/Translator (free version)

2022-04-21 06:59 UTC, sshaman1101 commented
LGTM, @un1tT  please take a look

2022-04-21 07:39 UTC, un1tT commented on frontend/src/store/settings/constants.ts
> +export const SETTINGS_URL = SETTINGS;
It's better to remove all of the `..._URL` constants then, because now it makes no sence. This way, all of the api calls will just use constants directly from `src/constants/apiPaths/index.ts`

2022-04-21 07:40 UTC, un1tT requested changes
Great idea, thank you for your contribution! Just a little change request from my side to make implementation more good-looking.

2022-04-21 16:34 UTC, instingt commented
Make sense. Just pushed update

2022-04-22 06:40 UTC, un1tT approved these changes

2022-04-22 06:41 UTC, merged